services:
  db:
    image: postgres:15-alpine
    container_name: biblioteca-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - biblioteca-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: biblioteca-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - biblioteca-net

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: biblioteca-frontend
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      - api
    networks:
      - biblioteca-net

volumes:
  pgdata:

networks:
  biblioteca-net:
    driver: bridge