# services:
#   db:
#     image: postgres:15-alpine
#     container_name: biblioteca-db
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgrespassword
#       POSTGRES_DB: biblioteca
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - biblioteca-net
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d biblioteca"]
#       interval: 5s
#       timeout: 5s
#       retries: 10

#   api:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: biblioteca-api
#     restart: unless-stopped
#     ports:
#       - "3000:3000"
#     environment:
#       PORT: 3000
#       JWT_SECRET: minha_chave_super_secreta_123
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: postgrespassword
#       DB_NAME: biblioteca
#     depends_on:
#       db:
#         condition: service_healthy
#     networks:
#       - biblioteca-net

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     container_name: biblioteca-frontend
#     restart: unless-stopped
#     ports:
#       - "8080:80"
#     depends_on:
#       - api
#     networks:
#       - biblioteca-net

# volumes:
#   pgdata:

# networks:
#   biblioteca-net:
#     driver: bridge
